[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/ws/*"
  to = "https://sharencrypt-relay.netlify.app/ws/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200